name: chat_app_final
description: Đồ án chat app Flutter + Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3

  # Auth & utils
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^8.0.0
  injectable: ^2.5.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3

  # Video Call
  zego_uikit: ^2.24.2
  zego_uikit_prebuilt_call: ^4.16.3
  zego_uikit_signaling_plugin: ^2.8.2
  
  # Dependencies bổ sung
  device_info_plus: ^11.1.0
  package_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
